---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: bento/centos-6.7
  - name: bento/centos-7.1

suites:
  - name: default
    run_list:
      - recipe[php]
      - recipe[mailcatcher-ng]
      - recipe[mailcatcher-ng::php]
      - recipe[mailcatcher-ng::postfix]
